export const TRPC_ERROR_CODES_BY_API_CODE: TRPCErrorCode = {
	400: "BAD_REQUEST",
	401: "UNAUTHORIZED",
	403: "FORBIDDEN",
	404: "NOT_FOUND",
	405: "METHOD_NOT_SUPPORTED",
	408: "TIMEOUT",
	409: "CONFLICT",
	412: "PRECONDITION_FAILED",
	413: "PAYLOAD_TOO_LARGE",
	429: "TOO_MANY_REQUESTS",
	499: "CLIENT_CLOSED_REQUEST",
	500: "INTERNAL_SERVER_ERROR",
} as const;

interface TRPCErrorCode {
	[key: number]: (typeof codes)[number];
}

const codes = [
	"PARSE_ERROR",
	"BAD_REQUEST",
	"INTERNAL_SERVER_ERROR",
	"UNAUTHORIZED",
	"FORBIDDEN",
	"NOT_FOUND",
	"METHOD_NOT_SUPPORTED",
	"TIMEOUT",
	"CONFLICT",
	"PRECONDITION_FAILED",
	"PAYLOAD_TOO_LARGE",
	"TOO_MANY_REQUESTS",
	"CLIENT_CLOSED_REQUEST",
] as const;
